FORMAT: 1A
HOST: http://trunk.cocoapods.org/api/v1

# trunk.cocoapods.org

API documentation for CocoaPods Trunk.

# Group Sessions

API for managing sessions.

## Session Collection [/sessions]

### Create a Session [POST]

+ Request (application/json)

        { "email": "kyle@cocoapods.org" }

        { "email": "kyle@cocoapods.org", "name": "Kyle Fuller" }

        { "email": "kyle@cocoapods.org", "name": "Kyle Fuller", "description": "Office Mac" }

+ Response 201 (application/json)

        {
          "created_at": "2014-05-04 15:20:19 +0200",
          "token": "527d11fe429f3426cb8dbeba183a0d80",
          "valid_until": "2014-09-09 15:20:19 +0200",
          "verified": false,
          "created_from_ip": "1.2.3.4",
          "description": "Office Mac"
        }

### Retrieve Sessions [GET]

+ Request

    + Headers

            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80


+ Response 200 (application/json)

        {
          "created_at": "2014-04-21 23:08:00 +0200",
          "email": "kyle@cocoapods.org",
          "name": "Kyle Fuller",
          "sessions": [
            {
              "created_at": "2014-05-04 15:20:19 +0200",
              "valid_until": "2014-09-09 15:20:19 +0200",
              "verified": false
            },
            {
              "created_at": "2014-05-04 15:20:20 +0200",
              "valid_until": "2014-09-09 15:20:20 +0200",
              "verified": true
            }
          ]
        }

+ Response 401 (application/json)

        { "error": "Authentication token is invalid or unverified." }

### Delete a session [DELETE]

+ Request

    + Headers

            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80

+ Response 201

### DELETE /sessions/all

+ Request

    + Headers

            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80

+ Response 201

# Group Pods

API for managing pods.

## POST /pods

+ Request (application/json)

    + Headers

            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80

    + Body

            {
              "name": "QueryKit",
              "version": "0.8.3",
              "authors": {
                "Kyle Fuller": "inbox@kylefuller.co.uk"
              },
              "social_media_url": "http://twitter.com/kylefuller",
              "source": {
                "git": "https://github.com/QueryKit/QueryKit.git",
                "tag": "0.8.3"
              },
              "source_files": [
                "QueryKit/*.{h}",
                "QueryKit/ObjectiveC/*.{h,m}"
              ],
              "requires_arc": true
            }

+ Response 302

    + Headers

            Location: https://trunk.cocoapods.org/api/v1/pods/QueryKit/versions/0.8.3

+ Response 403 (application/json)

        { "error": "You are not allowed to push new versions for this pod." }

+ Response 503 (application/json)

        { "error": "Push access is currently disabled." }

## GET /pods/{name}

+ Response 200 (application/json)

        {
          "versions": [
            {
              "created_at": "2014-04-13 23:04:37 +0000",
              "name": "1.0.0"
            }
          ],
          "owners": [
            {
              "created_at": "2014-04-13 22:49:56 +0000",
              "email": "inbox@kylefuller.co.uk",
              "name": "Kyle Fuller"
            }
          ]
        }

## GET /pods/{name}/versions/{version}

+ Response 200 (application/json)

        {
            "messages": [{
                "2014-05-05 20:50:42 +0200": "Push for `KFData 1.0.2' initiated."
            }, {
                "2014-05-05 20:50:42 +0200": "Push for `KFData 1.0.2' has been pushed (0.000307 s)."
            }],
            "data_url": "https://raw.githubusercontent.com/CocoaPods/Specs/355a6a1e6065b4a939e688b0bc42d2a74dc4fcf7/Specs/KFData/1.0.2/KFData.podspec.json"
        }

## PATCH /pods/{name}/owners

+ Request (application/json)

    + Headers

            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80

    + Body

            { "email": "eloy.de.enige@gmail.com" }

+ Response 200 (application/json)

        [
          {
            "created_at": "2014-04-13 22:49:56 +0000",
            "email": "inbox@kylefuller.co.uk",
            "name": "Kyle Fuller"
          }, {
            "created_at": "2014-04-01 00:00:00 +0000",
            "email": "eloy.de.enige@gmail.com",
            "name": "Eloy Durán"
          }
        ]

