FORMAT: 1A
HOST: http://trunk.cocoapods.org/api/v1

# cocoapods
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Sessions
API for managing sessions.

## Session Collection [/sessions]

### Get your current Session [GET]

+ Request

    + Headers
    
            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80


+ Response 200 (application/json)

        {
          "created_at": "2014-04-21 23:08:00 +0200",
          "email": "kyle@cocoapods.org",
          "name": "Kyle Fuller",
          "sessions": [{
              "created_at": "2014-05-04 15:20:19 +0200",
              "valid_until": "2014-09-09 15:20:19 +0200",
              "verified": false
          },
          {
              "created_at": "2014-05-04 15:20:20 +0200",
              "valid_until": "2014-09-09 15:20:20 +0200",
              "verified": true
          }]
        }

+ Response 401 (application/json)

        { "error": "Authentication token is invalid or unverified." }

### Create a Session [POST]

+ Request (application/json)

        { "email": "kyle@cocoapods.org", "name": "Kyle Fuller" }

+ Response 201 (application/json)

        {
          "created_at": "2014-05-04 15:20:19 +0200",
          "token": "527d11fe429f3426cb8dbeba183a0d80",
          "valid_until": "2014-09-09 15:20:19 +0200",
          "verified": false
        }

### Deletes your current Session [DELETE]

+ Request

    + Headers
    
            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80


+ Response 201

# Group Pods
API for managing pods.

## POST /pods

+ Request (application/json)

        {
            "name": "KFData",
            "version": "1.0.2",
            "license": "BSD",
            "summary": "Lightweight Core Data wrapper.",
            "homepage": "https://github.com/kylef/KFData",
            "authors": {
                "Kyle Fuller": "inbox@kylefuller.co.uk"
            },
            "social_media_url": "https://twitter.com/kylefuller",
            "source": {
                "git": "https://github.com/kylef/KFData.git",
                "tag": "1.0.2"
            },
            "requires_arc": true,
            "platforms": {
                "osx": "10.7",
                "ios": "5.0"
            },
            "default_subspec": "Essentials",
            "header_dir": "KFData",
            "subspecs": [{
                "name": "Attribute",
                "ios": {
                    "source_files": "KFData/Attribute/*.{h,m}"
                },
                "osx": {
                    "source_files": "KFData/Attribute/*.{h,m}"
                }
            }, {
                "name": "Manager",
                "ios": {
                    "source_files": "KFData/Manager/*.{h,m}"
                },
                "osx": {
                    "source_files": "KFData/Manager/*.{h,m}"
                }
            }, {
                "name": "Core",
                "ios": {
                    "frameworks": "CoreData",
                    "source_files": ["KFData/KFData.h", "KFData/Core/*.{h,m}"]
                },
                "osx": {
                    "frameworks": "CoreData",
                    "source_files": "KFData/Core/*.{h,m}"
                }
            }, {
                "name": "Store",
                "ios": {
                    "frameworks": "CoreData",
                    "source_files": "KFData/Store/*.{h,m}",
                    "public_header_files": "KFData/Store/KFDataStore.h",
                    "private_header_files": "KFData/Store/KFDataStoreInternal.h"
                },
                "osx": {
                    "frameworks": "CoreData",
                    "source_files": "KFData/Store/*.{h,m}",
                    "public_header_files": "KFData/Store/KFDataStore.h",
                    "private_header_files": "KFData/Store/KFDataStoreInternal.h"
                }
            }, {
                "name": "UI",
                "dependencies": {
                    "KFData/Essentials": []
                },
                "platforms": {
                    "ios": null
                },
                "ios": {
                    "frameworks": "UIKit",
                    "source_files": "KFData/UI/*.{h,m}"
                }
            }, {
                "name": "Essentials",
                "dependencies": {
                    "KFData/Core": [],
                    "KFData/Store": [],
                    "KFData/Attribute": [],
                    "KFData/Manager": []
                },
                "ios": {
                    "dependencies": {
                        "KFData/UI": []
                    }
                }
            }, {
                "name": "Compatibility",
                "dependencies": {
                    "KFData/Core": [],
                    "KFData/Manager": []
                },
                "header_dir": "KFData/Compatibility",
                "source_files": "KFData/Compatibility/*.{h,m}"
            }]
        }

+ Response 302

    + Headers

            Location: https://trunk.cocoapods.org/api/v1/pods/KFData/versions/1.0.2

+ Response 403 (application/json)

        { "error": "You are not allowed to push new versions for this pod." }

+ Response 503 (application/json)

        { "error": "Push access is currently disabled." }

## GET /pods/{name}

+ Response 200 (application/json)

        {
          "versions": [
            {
              "created_at": "2014-04-13 23:04:37 +0000",
              "name": "1.0.0"
            }
          ],
          "owners": [
            {
              "created_at": "2014-04-13 22:49:56 +0000",
              "email": "inbox@kylefuller.co.uk",
              "name": "Kyle Fuller"
            }
          ]
        }
        
## GET /pods/{name}/versions/{version}

+ Response 200 (application/json)

        {
            "messages": [{
                "2014-05-05 20:50:42 +0200": "Push for `KFData 1.0.2' initiated."
            }, {
                "2014-05-05 20:50:42 +0200": "Push for `KFData 1.0.2' has been pushed (0.000307 s)."
            }],
            "data_url": "https://raw.githubusercontent.com/CocoaPods/Specs/355a6a1e6065b4a939e688b0bc42d2a74dc4fcf7/Specs/KFData/1.0.2/KFData.podspec.json"
        }

## PATCH /pods/{name}/owners

+ Request (application/json)

        {}

+ Response 200 (application/json)

        {}
