FORMAT: 1A
HOST: http://trunk.cocoapods.org/api/v1

# cocoapods
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Sessions
API for managing sessions.

## Session Collection [/sessions]

### Get your current Session [GET]

+ Request

    + Headers
    
            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80


+ Response 200 (application/json)

        {
          "created_at": "2014-04-21 23:08:00 +0200",
          "email": "kyle@cocoapods.org",
          "name": "Kyle Fuller",
          "sessions": [{
              "created_at": "2014-05-04 15:20:19 +0200",
              "valid_until": "2014-09-09 15:20:19 +0200",
              "verified": false
          },
          {
              "created_at": "2014-05-04 15:20:20 +0200",
              "valid_until": "2014-09-09 15:20:20 +0200",
              "verified": true
          }]
        }

+ Response 401 (application/json)

        { "error": "Authentication token is invalid or unverified." }

### Create a Session [POST]

+ Request (application/json)

        { "email": "kyle@cocoapods.org", "name": "Kyle Fuller" }

+ Response 201 (application/json)

        {
          "created_at": "2014-05-04 15:20:19 +0200",
          "token": "527d11fe429f3426cb8dbeba183a0d80",
          "valid_until": "2014-09-09 15:20:19 +0200",
          "verified": false
        }

### Deletes your current Session [DELETE]

+ Request

    + Headers
    
            Authorization: Token 527d11fe429f3426cb8dbeba183a0d80


+ Response 201

# Group Pods
API for managing pods.

## POST /pods

+ Request (application/json)

        {}


+ Response 201 (application/json)

        {}
        
## GET /pods/{name}

+ Response 200 (application/json)

        {
          "versions": [
            {
              "created_at": "2014-04-13 23:04:37 +0000",
              "name": "1.0.0"
            }
          ],
          "owners": [
            {
              "created_at": "2014-04-13 22:49:56 +0000",
              "email": "inbox@kylefuller.co.uk",
              "name": "Kyle Fuller"
            }
          ]
        }
        
## GET /pods/{name}/versions/{version}

+ Response 200 (application/json)

        {
          "messages": [
            {
              "2014-04-13 23:04:37 +0000": "Version `NSAttributedString+CCLFormat 1.0.0' created via Github hook."
            }
          ],
          "data_url": "https:\/\/raw.github.com\/CocoaPods\/Specs\/6d2c71e76855ed066fe48db6ae3bee9bbf5972ba\/Specs\/NSAttributedString+CCLFormat\/1.0.0\/NSAttributedString+CCLFormat.podspec.json"
        }
        
## PATCH /pods/{name}/owners

+ Request (application/json)

        {}

+ Response 200 (application/json)

        {}
